download:
	git clone https://github.com/pano-takanan-history/blumpanotacana cldf-resources/blumpanotacana
	git clone https://github.com/pano-takanan-history/oliveiraprotopanoan cldf-resources/oliveiraprotopanoan
	git clone https://github.com/pano-takanan-history/girardprototakanan cldf-resources/girardprototakanan
	git clone https://github.com/pano-takanan-history/valenzuelazariquieypanotakana cldf-resources/valenzuelazariquieypanotakana
	git clone https://github.com/pano-takanan-history/girardprotopanotakanan	cldf-resources/girardprotopanotakanan