download:
	git clone https://github.com/pano-takanan-history/blumpanotacana cldf-resources/blumpanotacana --branch v1.2
	git clone https://github.com/pano-takanan-history/oliveiraprotopanoan cldf-resources/oliveiraprotopanoan --branch v1.2.0 
	git clone https://github.com/pano-takanan-history/girardprototakanan cldf-resources/girardprototakanan  --branch v1.0.0
	git clone https://github.com/pano-takanan-history/valenzuelazariquieypanotakana cldf-resources/valenzuelazariquieypanotakana --branch v1.0.0
